media: files
content:
 - name: recipes
   label: Recipes
   type: collection
   path: _recipes
   view: 
     fields: [title, author, date]
   fields:
    - { name: title, label: Title, type: string }
    - { name: image, label: Image, type: image }
    - { name: date, label: Date, type: date }
    - { name: ingredients, label: Ingredients, type: rich-text }
    - { name: directions, label: Directions, type: rich-text }
    - name: author
      type: select
      label: Author
      default: romano
      options:
        values:
        - value: farina
          label: Farina
        - value: reynolds
          label: Reynolds
        - value: romano
          label: Romano